# -*- coding: utf-8 -*-
"""Banglawash.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14ghynTryTE4-hljCYbB9RJ05_cEEd9m3
"""

tc = int(input())
for i in range(tc):
  n = int(input())
  s = input()
  c = n
  b = 0
  w = 0
  t = 0
  a = 0
  for j in range(len(s)):
    if s[j]=='B':
      b=b+1
    elif s[j]=='W':
      w=w+1
    elif s[j]=='T':
      t=t+1
    elif s[j]=='A':
      a=a+1
      n=n-1
  if b==n and b!=0:
    print(f"Case {i+1}: BANGLAWASH")
  elif w==n and w!=0:
    print(f"Case {i+1}: WHITEWASH")
  elif b>w:
    print(f"Case {i+1}: BANGLADESH {b} - {w}")
  elif w>b:
    print(f"Case {i+1}: WWW {w} - {b}")
  elif b==w and a!=c:
    print(f"Case {i+1}: DRAW {b} {t}")
  elif a==c:
    print(f"Case {i+1}: ABANDONED")